name: fansedu
description: "Fansedu is E-Learning develop by Fans Technology"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # firebase
  firebase_analytics: ^10.1.1
  firebase_messaging: ^14.6.9
  firebase_remote_config: ^3.0.9
  firebase_dynamic_links: ^5.3.7

  # user-interface
  awesome_dialog: ^3.0.2
  carousel_slider: ^5.0.0
  dotted_border: ^2.0.0+3
  email_validator: ^3.0.0
  flutter_html: 3.0.0-beta.2
  flutter_markdown: ^0.7.4+3
  flutter_screenutil: ^5.6.1
  flutter_svg: ^2.0.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^4.1.0
  just_the_tooltip: ^0.0.12
  markdown: ^7.0.0
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0
  table_calendar: ^3.0.9
  timelines_plus: ^1.0.4
  tutorial_coach_mark: ^1.2.11

  # encryption
  encrypt: ^5.0.3
  pointycastle: ^3.6.2

  # utils
  alice: ^1.0.0-dev.12
  alice_dio: ^1.0.6
  auto_route: ^8.1.4
  basic_utils: ^5.7.0
  build_runner: ^2.3.3
  cached_network_image: ^3.2.3
  connectivity_plus: ^6.1.0
  dartz: ^0.10.1
  device_info_plus: ^9.1.2
  dio: ^5.4.0
  equatable: ^2.0.5
  external_path: ^2.0.1
  firebase_core: ^2.4.1
  flutter_bloc: ^8.1.1
  flutter_dash: ^1.0.0
  flutter_local_notifications: ^17.1.2
  flutter_timezone: ^3.0.1
  flutter_secure_storage: ^9.2.2
  flutter_spinkit: ^5.1.0
  freezed_annotation: ^2.2.0
  get_it: ^8.0.2
  intl: ^0.19.0
  json_annotation: ^4.8.0
  jwt_decode: ^0.3.1
  keyboard_dismisser: ^3.0.0
  open_filex: ^4.3.2
  path_provider: ^2.0.11
  permission_handler: ^11.1.0
  provider: ^6.0.5
  pull_to_refresh: ^2.0.0
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.6
  share_plus: ^10.1.2
  store_redirect: ^2.0.1
  uuid: ^4.4.2
  syncfusion_flutter_datepicker: ^27.2.4
  collection: ^1.18.0
  flutter_background_service: ^5.0.5
  flutter_card_swiper: ^7.0.1

  # local-db
  hive: ^2.2.3
  shared_preferences: ^2.1.0

  syncfusion_flutter_core: ^27.2.4
  syncfusion_flutter_gauges: ^27.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^8.0.0
  freezed: ^2.3.2
  hive_generator:
    git:
      url: https://github.com/yura2000/hive.git
      ref: master
      path: hive_generator/
  json_serializable: ^6.6.1
  analyzer: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/jpg/
    - assets/svg/
    - assets/pdf
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
        - asset: assets/fonts/PlusJakartaSans-BoldItalic.ttf
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
        - asset: assets/fonts/PlusJakartaSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
        - asset: assets/fonts/PlusJakartaSans-ExtraLightItalic.ttf
        - asset: assets/fonts/PlusJakartaSans-Italic.ttf
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
        - asset: assets/fonts/PlusJakartaSans-LightItalic.ttf
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
        - asset: assets/fonts/PlusJakartaSans-MediumItalic.ttf
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
        - asset: assets/fonts/PlusJakartaSans-SemiBoldItalic.ttf

flutter_intl:
  enabled: true