// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw2n6dEBdLlxjzgCECqbUnmOsgquY28xs',
    appId: '1:874639475682:web:61533b89d4aab6dc2befbb',
    messagingSenderId: '874639475682',
    projectId: 'fansedu-mobile',
    authDomain: 'fansedu-mobile.firebaseapp.com',
    storageBucket: 'fansedu-mobile.firebasestorage.app',
    measurementId: 'G-506DCJX9F6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc2Dva63FEDHFIVfz0WP1_UBiYpnejiyk',
    appId: '1:874639475682:android:cfe303304f8903ab2befbb',
    messagingSenderId: '874639475682',
    projectId: 'fansedu-mobile',
    storageBucket: 'fansedu-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2gG7O896DzvlGHNCvdSwrKq4olzYxwhc',
    appId: '1:874639475682:ios:3823f824b62970782befbb',
    messagingSenderId: '874639475682',
    projectId: 'fansedu-mobile',
    storageBucket: 'fansedu-mobile.firebasestorage.app',
    iosBundleId: 'com.meirusfandi.fansedu.fansedu.RunnerTests',
  );
}
